version: '2'
services:
# HOSSTED APP
  elastichq:
    image: elastichq/elasticsearch-hq
    container_name: elastichq
    restart: "unless-stopped"
    environment:
     - HQ_ENABLE_SSL=true
     - HQ_VERIFY_CERTS=false
    expose:
     - 5000
#    volumes:
#     - ./data/elastichq:/src/db
#    command:
#      sh -x -c 'sed -i -r -e "s/_sqlalchemy_database_uri =.*/_sqlalchemy_database_uri = "sqlite:///" + os.path.join(BASEPATH, "db" , "elastichq.db")/" /src/elastichq/config/settings.py && exec supervisord -c /etc/supervisor/supervisord.conf'
    labels:
     - traefik.enable=true
     - "traefik.http.routers.$PROJECT_NAME.rule=Host(`${PROJECT_BASE_URL}`)"
     - "traefik.http.routers.$PROJECT_NAME.entrypoints=websecure"
     - "traefik.http.routers.$PROJECT_NAME.tls.certresolver=myhttpchallenge"
     - traefik.http.middlewares.rhttps.redirectscheme.scheme=https
     - traefik.http.middlewares.rhttps.redirectscheme.permanent=true
     - "traefik.http.routers.web-insecure.rule=Host(`${PROJECT_BASE_URL}`)"
     - traefik.http.routers.web-insecure.entrypoints=web
     - traefik.http.routers.web-insecure.middlewares=rhttps
     - "traefik.http.middlewares.tauth.basicauth.removeheader=true"
     - "traefik.http.middlewares.tauth.basicauth.usersfile=letsencrypt/.htpass"
     - "traefik.http.routers.$PROJECT_NAME.middlewares=tauth"
     - "traefik.http.services.$PROJECT_NAME.loadbalancer.server.port=5000"
     - "traefik.http.routers.$PROJECT_NAME.priority=100"
# HOSSTED WRAPPER
  traefik:
    extends:
      file: hossted/hossted-traefik.yml
      service: hossted-traefik
# monitoring part disabled by default

#    hossted-monitoring-node:
#      extends:
#        file: hossted/hossted-node-exporter.yml
#        service: hossted-node-exporter

# end of monitoring part

# loki part disabled by default

#    hossted-logging-app:
#      extends:
#        file: hossted/hossted-loki.yml
#        service: hossted-loki


# end of loki part

# promtail part disabled by default

#    hossted-logging-promotail:
#      extends:
#        file: hossted/hossted-promtail.yml
#        service: hossted-promtail


# end of promtail part

  maintenance-page:
    extends:
      file: hossted/hossted-maintenance-page.yml
      service: hossted-maintenance-page
# HOSSTED WRAPPER END
