version: '2'

services:
### HOSSTED APP
  sonarqube:
    image: sonarqube:latest
#    ports:
#      - '9000:9000'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/hossted
      SONAR_JDBC_USERNAME: hossted
      SONAR_JDBC_PASSWORD: hosstedpass
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    labels:
      - traefik.enable=true
      - "traefik.http.routers.$PROJECT_NAME.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.$PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$PROJECT_NAME.tls.certresolver=myhttpchallenge"
      - traefik.http.routers.$PROJECT_NAME.middlewares=securedheaders
        # commented out , tauth
      - traefik.http.middlewares.rhttps.redirectscheme.scheme=https
      - traefik.http.middlewares.rhttps.redirectscheme.permanent=true
      - "traefik.http.routers.web-insecure.rule=Host(`${PROJECT_BASE_URL}`)"
      - traefik.http.routers.web-insecure.entrypoints=web
      - traefik.http.routers.web-insecure.middlewares=rhttps
      - "traefik.http.services.$PROJECT_NAME.loadbalancer.server.port=9000"
      - "traefik.http.routers.$PROJECT_NAME.priority=100"
    restart: always
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: hossted
      POSTGRES_PASSWORD: hosstedpass
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

#  HOSSTED WRAPPER
  traefik:
    extends:
      file: hossted/hossted-traefik.yml
      service: hossted-traefik
  node-exporter:
    extends:
      file: hossted/hossted-node-exporter.yml
      service: hossted-node-exporter
  maintenance-page:
    extends:
      file: hossted/hossted-maintenance-page.yml
      service: hossted-maintenance-page

volumes:
  postgresql:
    driver: local
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
