server:
  log_level: debug
metrics:
  wal_directory: /var/lib/agent/wal
  global:
    scrape_interval: 30s
    external_labels:
      uuid: ${UUID}
      cluster: "compose"
  configs:
  - name: integrations
    remote_write:
      - url: ${MIMIR_URL}
        basic_auth:
          username: ${MIMIR_USERNAME}
          password: ${MIMIR_PASSWORD}
    scrape_configs:
    - job_name: 'cadvisor'
      static_configs:
        - targets: ['cadvisor:8080']
    - job_name: 'node_exporter'
      static_configs:
        - targets: ['node_exporter:9100']   
