server:
  log_level: debug
metrics:
  wal_directory: /var/lib/agent/wal
  global:
    scrape_interval: 30s
    external_labels:
      uuid: ${UUID}
      cluster: "compose"
  configs:
  - name: integrations
    remote_write:
      - url: ${MIMIR_URL}
        basic_auth:
          username: ${MIMIR_USERNAME}
          password: ${MIMIR_PASSWORD}
    scrape_configs:
    - job_name: 'cadvisor'
      static_configs:
        - targets: ['cadvisor:8080']
    - job_name: 'node_exporter'
      static_configs:
        - targets: ['node_exporter:9100']
loki:
- name: integrations
  remote_write:
    - url: "https://loki-hossted-infra.gke-dev.linnovate.net/loki/api/v1/push"
      basic_auth:
        username: "loki"
        password: "b10igI1R09MlUmz"
  configs:
    - name: integrations/docker
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: integrations/docker
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - target_label: 'job'
              replacement: 'integrations/docker'
            - target_label: 'instance'
              replacement: '__address__'
            - source_labels: ['__meta_docker_container_name']
              regex: '/(.*)'
              target_label: 'container'
            - source_labels: ['__meta_docker_container_log_stream']
              target_label: 'stream'
