name: Build Go Binary

on:
  push:
    branches:
      - dev
      - main
    # tag should with 3 numbers separated by dot, i.e. 0.4.6
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - dev
      - main
jobs:
  development:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    name: Development Environment
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      version: "dev"
      environment: "dev"
      is-production: false
      

  production:
    if: startsWith(github.ref, 'refs/tags/')
    name: Production Environment
    uses: ./.github/workflows/reusable.yml
    secrets: inherit
    with:
      version: "${{ github.ref_name }}"
      environment: "prod"
      is-production: true
