name: Build Go Binary

on:
  push:
    branches:
      - dev
      - cli-activate 
      - main
  pull_request:
    branches:
      - dev
      - cli-activate
      - main
jobs:
  development:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/cli-activate'
    name: Development Environment
    uses: ./.github/workflows/reusable.yml
    with:
      go-version: '1.19'
      LOKI_URL: ${{ secrets.LOKI_URL }}
      HOSSTED_API_URL: ${{ secrets.HOSSTED_API_URL }}
      MIMIR_URL: ${{ secrets.MIMIR_URL }}
      version: "dev"
      environment: "dev"
      

  production:
    if: github.ref == 'refs/heads/main'
    name: Production Environment
    uses: ./.github/workflows/reusable.yml
    with:
      go-version: '1.19'
      loki_url: ${{ secrets.LOKI_URL }}
      hossted_api_url: ${{ secrets.HOSSTED_API_URL }}
      mimir_url: ${{ secrets.MIMIR_URL }}
      version: "${{ github.ref_name }}"
      environment: "prod"
