name: Build Go Binary

on:
  push:
    branches:
      - dev
      - cli-activate 
      - main
  pull_request:
    branches:
      - dev
      - cli-activate
      - main
jobs:
  development:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/cli-activate'
    name: Development Environment
    uses: ./.github/workflows/reusable.yml
    with:
      go-version: '1.19'
      version: "dev"
      environment: "dev"
      

  production:
    if: github.ref == 'refs/heads/main'
    name: Production Environment
    uses: ./.github/workflows/reusable.yml
    with:
      go-version: '1.19'
      version: "${{ github.ref_name }}"
      environment: "prod"
