name: Reusable Workflow

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      version:
        required: true
        type: string
      environment:
        required: true
        type: string
      is-production:
        required: true
        type: boolean

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

    - name: Inject secrets and build
      env:
          LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
          LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
          MIMIR_USERNAME: ${{ secrets.MIMIR_USERNAME }}
          MIMIR_PASSWORD: ${{ secrets.MIMIR_PASSWORD }}
          HOSSTED_AUTH_TOKEN: ${{ secrets.HOSSTED_AUTH_TOKEN }}
          LOKI_URL: ${{ secrets.LOKI_URL }}
          HOSSTED_API_URL: ${{ secrets.HOSSTED_API_URL }}
          MIMIR_URL: ${{ secrets.MIMIR_URL }}
          COMMIT_HASH: ${{ github.sha }}
          VERSION: ${{ inputs.version }}
          ENVIRONMENT: ${{ inputs.environment }}
      run: |
        BUILD_TIMESTAMP="$(date '+%Y-%m-%d')"
        PACKAGE=github.com/hossted/cli
        SERVICE_COMMON_PACKAGE=${PACKAGE}/hossted/service/common
        COMMON_FLAGS=" -X '${PACKAGE}/cmd.VERSION=${VERSION}' -X '${PACKAGE}/cmd.ENVIRONMENT=${ENVIRONMENT}' -X '${PACKAGE}/cmd.COMMITHASH=${COMMIT_HASH}' -X '${PACKAGE}/cmd.BUILDTIME=${BUILD_TIMESTAMP}' -X '${SERVICE_COMMON_PACKAGE}.LOKI_URL=${LOKI_URL}' -X '${SERVICE_COMMON_PACKAGE}.LOKI_USERNAME=${LOKI_USERNAME}' -X '${SERVICE_COMMON_PACKAGE}.LOKI_PASSWORD=${LOKI_PASSWORD}' -X '${SERVICE_COMMON_PACKAGE}.MIMIR_USERNAME=${MIMIR_USERNAME}' -X '${SERVICE_COMMON_PACKAGE}.MIMIR_PASSWORD=${MIMIR_PASSWORD}' -X '${SERVICE_COMMON_PACKAGE}.HOSSTED_API_URL=${HOSSTED_API_URL}' -X '${SERVICE_COMMON_PACKAGE}.MIMIR_URL=${MIMIR_URL}' -X '${SERVICE_COMMON_PACKAGE}.HOSSTED_AUTH_TOKEN=${HOSSTED_AUTH_TOKEN}'"
        echo "COMMON_FLAGS= $COMMON_FLAGS"
        GOOS=linux GOARCH=amd64 go build -v -ldflags "$COMMON_FLAGS"  -o hossted-linux-amd64
        GOOS=darwin GOARCH=amd64 go build -v -ldflags "$COMMON_FLAGS" -o hossted-darwin-amd64
    
    - name: Test Version of binary file
      run: |
        echo "Checking version of binary file..."
        chmod 777 hossted-linux-amd64
        ./hossted-linux-amd64 version
        
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: hossted-linux-amd64
        path: ./hossted-linux-amd64
        if-no-files-found: error
        
    - name: Upload OSx binary
      uses: actions/upload-artifact@v4
      with:
        name: hossted-darwin-amd64
        path: ./hossted-darwin-amd64
        if-no-files-found: error
    
    - name: Create GitHub Release
      if: ${{ inputs.is-production }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automated release created for tag ${{ github.ref_name }}.
          This release includes the latest production build.
        draft: true
        prerelease: false
    
