name: Reusable Workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment:
        required: true
        type: string
      is-production:
        required: true
        type: boolean

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Inject secrets and build
      env:
          LOKI_USERNAME: ${{ secrets.LOKI_USERNAME }}
          LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
          MIMIR_USERNAME: ${{ secrets.MIMIR_USERNAME }}
          MIMIR_PASSWORD: ${{ secrets.MIMIR_PASSWORD }}
          HOSSTED_AUTH_TOKEN: ${{ secrets.HOSSTED_AUTH_TOKEN }}
          LOKI_URL: ${{ secrets.LOKI_URL }}
          HOSSTED_API_URL: ${{ secrets.HOSSTED_API_URL }}
          MIMIR_URL: ${{ secrets.MIMIR_URL }}
          COMMIT_HASH: ${{ github.sha }}
          VERSION: ${{ inputs.version }}
          ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "${{ inputs.is-production }}" == "true" ]; then
          make -f Makefile linux
          make -f Makefile osx
        else
          make -f Makefile dev
        fi
    
    - name: Test Version of binary file
      run: |
        echo "Checking version of binary file..."
        if [ "${{ inputs.is-production }}" == "true" ]; then
          chmod 777 bin/linux/hossted-linux-amd64 && ./bin/linux/hossted-linux-amd64 version
        else
          chmod 777  bin/dev/hossted && ./bin/dev/hossted version
        fi
        
    - name: Upload Linux binary
      if: ${{ inputs.is-production }}
      uses: actions/upload-artifact@v4
      with:
        name: hossted-linux-amd64
        path: ./bin/linux/hossted-linux-amd64
        if-no-files-found: error
        
    - name: Upload OSx binary
      if: ${{ inputs.is-production }}
      uses: actions/upload-artifact@v4
      with:
        name: hossted-darwin-amd64
        path: ./bin/osx/hossted-darwin-amd64
        if-no-files-found: error
    
    - name: Upload DEV binary
      if: ${{ !inputs.is-production }}
      uses: actions/upload-artifact@v4
      with:
        name: hossted
        path: ./bin/dev/hossted
        if-no-files-found: error
    
    - name: Create GitHub Release
      if: ${{ inputs.is-production }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automated release created for tag ${{ github.ref_name }}.
          This release includes the latest production build.
        draft: true
        prerelease: false
    
